import os, sys
#import background_rc
from FileDeepLerner import GoDeepInFile
try:
    import PyQt5
    from PyQt5 import QtCore, QtGui, QtWidgets
except:
    try:
        os.system("pip install pyqt5")
        os.system("pip install pyqt5-tools")
        from PyQt5 import QtCore, QtGui, QtWidgets
    except:
        print("[ - ] - Could not install pyqt5 =======> Graphique Not working")
        exit(2)
from AIModels import DeepLerner


def launch(models: DeepLerner):
    app = QtWidgets.QApplication(sys.argv)
    windows = QtWidgets.QMainWindow()
    diabete = Ui_Diabete(models)
    diabete.setupUi(windows)
    diabete.retranslateUi(windows)
    windows.show()
    sys.exit(app.exec_())


class Ui_Diabete(object):

    def clickPredictXLSX(self):
        self.typeError2.setText("")
        if self.deepLearningBrowse.isChecked() and self.machineLearningImport.isChecked():
            self.typeError2.setText("Only one must be selected")
        elif (not self.deepLearningBrowse.isChecked()) and (not self.machineLearningImport.isChecked()):
            self.typeError2.setText("You must select one")
        else:
            deeper = GoDeepInFile(self.labelImport.text())
            if self.deepLearningBrowse.isChecked():
                deeper.predictData(self.models.predictDeepLearning)
            if self.machineLearningImport.isChecked():
                deeper.predictData(self.models.predictMachineLearning)
            self.labelImport.setText("")
            self.typeError2.setText("")

    def getfiles(self):
        fileName, _ = QtWidgets.QFileDialog.getOpenFileName(None, 'Single File', '', '*.xlsx')
        self.labelImport.setText(fileName)

    def refreshFisrtPanel(self):
        self.pregnanciesError.setText("")
        self.skinThicknessError.setText("")
        self.diabetesPedigreeFunctionError.setText("")
        self.bloodPresureError.setText("")
        self.ageError.setText("")
        self.bmiError.setText("")
        self.insulinError.setText("")
        self.glucoseError.setText("")
        self.typeError.setText("")

    def refreshSecondPanel(self):
        self.typeError2.setText("")
        self.labelImport.setText("")

    def validFirstPanel(self):
        valid = True
        pregnanciesEdit = self.pregnanciesEdit.text().strip()
        SkinThicknessEdit = self.skinThicknessEdit.text().strip()
        DiabetesPedigreeFunctionEdit = self.diabetesPedigreeFunctionEdit.text().strip()
        BloodPressureEdit = self.bloodPresureEdit.text().strip()
        AgeEdit = self.ageEdit.text().strip()
        BMIEdit = self.bmiEdit.text().strip()
        InsulinEdit = self.insulinEdit.text().strip()
        GlucoseEdit = self.glucoseEdit.text().strip()

        try:
            pregnanciesEdit = float(pregnanciesEdit)
        except ValueError:
            valid = False
            self.pregnanciesError.setText("Valeur numérique")

        try:
            SkinThicknessEdit = float(SkinThicknessEdit)
        except ValueError:
            valid = False
            self.skinThicknessError.setText("Valeur numérique")

        try:
            DiabetesPedigreeFunctionEdit = float(DiabetesPedigreeFunctionEdit)
        except ValueError:
            valid = False
            self.diabetesPedigreeFunctionError.setText("Valeur numérique")

        try:
            BloodPressureEdit = float(BloodPressureEdit)
        except ValueError:
            valid = False
            self.bloodPresureError.setText("Valeur numérique")

        try:
            AgeEdit = float(AgeEdit)
        except ValueError:
            valid = False
            self.ageError.setText("Valeur numérique")

        try:
            BMIEdit = float(BMIEdit)
        except ValueError:
            valid = False
            self.bmiError.setText("Valeur numérique")

        try:
            InsulinEdit = float(InsulinEdit)
        except ValueError:
            valid = False
            self.insulinError.setText("Valeur numérique")

        try:
            GlucoseEdit = float(GlucoseEdit)
        except ValueError:
            valid = False
            self.glucoseError.setText("Valeur numérique")
        checkBoxMachineLearning = False
        checkBoxDeepLearning = False
        if self.machineLearningCheckbox.isChecked():
            checkBoxMachineLearning = True

        if self.deepLearningCheckbox.isChecked():
            checkBoxDeepLearning = True

        if checkBoxDeepLearning == False and checkBoxDeepLearning == False:
            self.typeError.setText("Selectionnez un modele")

        return valid, pregnanciesEdit, SkinThicknessEdit, DiabetesPedigreeFunctionEdit, BloodPressureEdit, AgeEdit, BMIEdit, InsulinEdit, GlucoseEdit,checkBoxDeepLearning,checkBoxMachineLearning

    def clicked(self):
        self.refreshFisrtPanel()
        valid, pregnanciesEdit, SkinThicknessEdit, DiabetesPedigreeFunctionEdit, BloodPressureEdit, AgeEdit, BMIEdit, InsulinEdit, GlucoseEdit,deepLearning,machineLearning = self.validFirstPanel()
        if valid:
            x = [[pregnanciesEdit, GlucoseEdit, BloodPressureEdit, SkinThicknessEdit, InsulinEdit, BMIEdit, DiabetesPedigreeFunctionEdit, AgeEdit]]
            if deepLearning:
                predictionsDeepLearning = self.models.predictDeepLearning(x)
                if predictionsDeepLearning == 0:
                    self.predictionDeepLearning.setText("La personne est non diabétique")
                else:
                    self.predictionDeepLearning.setText("La personne est diabetique")
            if machineLearning:
                predictionsMachineLearning = self.models.predictMachineLearning(x)
                if predictionsMachineLearning == 0:
                    self.predictionMachineLearning.setText("La personne est non diabétique")
                else:
                    self.predictionMachineLearning.setText("La personne est diabétique")
    def __init__(self, models: DeepLerner):
        self.models = models

    def setupUi(self, Diabete):
        Diabete.setObjectName("Diabete")
        Diabete.resize(1098, 867)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("images/logo.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap("../../Bureau/high-level-blood-sugar-vector-icon-diabetes-sign-81297690.jpg"),
                       QtGui.QIcon.Normal, QtGui.QIcon.On)
        Diabete.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(Diabete)
        self.centralwidget.setObjectName("centralwidget")
        self.Error = QtWidgets.QLabel(self.centralwidget)
        self.Error.setGeometry(QtCore.QRect(300, 470, 301, 31))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 105, 105))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(247, 52, 52))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(160, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(247, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 105, 105))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(247, 52, 52))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(160, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(247, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 105, 105))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(247, 52, 52))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(160, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        self.Error.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        self.Error.setFont(font)
        self.Error.setText("")
        self.Error.setObjectName("Error")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 1101, 851))
        self.label.setStyleSheet("background-image:url(images/background.jpg);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(90, 80, 931, 651))
        self.tabWidget.setStyleSheet("")
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setStyleSheet(
            "background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(0, 0, 0, 255), stop:0.33 rgba(0, 0, 0, 255), stop:0.34 rgba(255, 30, 30, 255), stop:0.66 rgba(255, 0, 0, 255), stop:0.67 rgba(255, 255, 0, 255), stop:1 rgba(255, 255, 0, 255));")
        self.tab.setObjectName("tab")
        self.pregnanciesEdit = QtWidgets.QLineEdit(self.tab)
        self.pregnanciesEdit.setGeometry(QtCore.QRect(180, 60, 211, 41))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pregnanciesEdit.setFont(font)
        self.pregnanciesEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.pregnanciesEdit.setObjectName("pregnanciesEdit")
        self.glucoseEdit = QtWidgets.QLineEdit(self.tab)
        self.glucoseEdit.setGeometry(QtCore.QRect(180, 140, 211, 41))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.glucoseEdit.setFont(font)
        self.glucoseEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.glucoseEdit.setObjectName("glucoseEdit")
        self.bloodPresureEdit = QtWidgets.QLineEdit(self.tab)
        self.bloodPresureEdit.setGeometry(QtCore.QRect(180, 220, 211, 41))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.bloodPresureEdit.setFont(font)
        self.bloodPresureEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.bloodPresureEdit.setObjectName("bloodPresureEdit")
        self.skinThicknessEdit = QtWidgets.QLineEdit(self.tab)
        self.skinThicknessEdit.setGeometry(QtCore.QRect(180, 300, 211, 41))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.skinThicknessEdit.setFont(font)
        self.skinThicknessEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.skinThicknessEdit.setObjectName("skinThicknessEdit")
        self.bmiEdit = QtWidgets.QLineEdit(self.tab)
        self.bmiEdit.setGeometry(QtCore.QRect(690, 140, 211, 41))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.bmiEdit.setFont(font)
        self.bmiEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.bmiEdit.setObjectName("bmiEdit")
        self.diabetesPedigreeFunctionEdit = QtWidgets.QLineEdit(self.tab)
        self.diabetesPedigreeFunctionEdit.setGeometry(QtCore.QRect(690, 220, 211, 41))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.diabetesPedigreeFunctionEdit.setFont(font)
        self.diabetesPedigreeFunctionEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.diabetesPedigreeFunctionEdit.setObjectName("diabetesPedigreeFunctionEdit")
        self.ageEdit = QtWidgets.QLineEdit(self.tab)
        self.ageEdit.setGeometry(QtCore.QRect(690, 300, 211, 41))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.ageEdit.setFont(font)
        self.ageEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.ageEdit.setObjectName("ageEdit")
        self.insulinEdit = QtWidgets.QLineEdit(self.tab)
        self.insulinEdit.setGeometry(QtCore.QRect(690, 60, 211, 41))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.insulinEdit.setFont(font)
        self.insulinEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.insulinEdit.setObjectName("insulinEdit")
        self.machineLearningCheckbox = QtWidgets.QCheckBox(self.tab)
        self.machineLearningCheckbox.setGeometry(QtCore.QRect(180, 380, 211, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.machineLearningCheckbox.setFont(font)
        self.machineLearningCheckbox.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.machineLearningCheckbox.setObjectName("machineLearningCheckbox")
        self.deepLearningCheckbox = QtWidgets.QCheckBox(self.tab)
        self.deepLearningCheckbox.setGeometry(QtCore.QRect(690, 380, 211, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.deepLearningCheckbox.setFont(font)
        self.deepLearningCheckbox.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.deepLearningCheckbox.setObjectName("deepLearningCheckbox")
        self.pushButton = QtWidgets.QPushButton(self.tab)
        self.pushButton.setGeometry(QtCore.QRect(340, 440, 311, 81))
        self.pushButton.clicked.connect(self.clicked)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(26)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("background-color: rgb(0, 255, 127);\n"
                                      "")
        self.pushButton.setObjectName("pushButton")
        self.predictionMachineLearning = QtWidgets.QLabel(self.tab)
        self.predictionMachineLearning.setGeometry(QtCore.QRect(340, 540, 301, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.predictionMachineLearning.setFont(font)
        self.predictionMachineLearning.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.predictionMachineLearning.setText("")
        self.predictionMachineLearning.setObjectName("predictionMachineLearning")
        self.predictionDeepLearning = QtWidgets.QLabel(self.tab)
        self.predictionDeepLearning.setGeometry(QtCore.QRect(340, 580, 301, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.predictionDeepLearning.setFont(font)
        self.predictionDeepLearning.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.predictionDeepLearning.setText("")
        self.predictionDeepLearning.setObjectName("predictionDeepLearning")
        self.pregnanciesLabel = QtWidgets.QLabel(self.tab)
        self.pregnanciesLabel.setGeometry(QtCore.QRect(20, 60, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pregnanciesLabel.setFont(font)
        self.pregnanciesLabel.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.pregnanciesLabel.setObjectName("pregnanciesLabel")
        self.glucoseLabel = QtWidgets.QLabel(self.tab)
        self.glucoseLabel.setGeometry(QtCore.QRect(20, 140, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.glucoseLabel.setFont(font)
        self.glucoseLabel.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.glucoseLabel.setObjectName("glucoseLabel")
        self.bloodPresureLabel = QtWidgets.QLabel(self.tab)
        self.bloodPresureLabel.setGeometry(QtCore.QRect(20, 220, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.bloodPresureLabel.setFont(font)
        self.bloodPresureLabel.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.bloodPresureLabel.setObjectName("bloodPresureLabel")
        self.skinThicknessLabel = QtWidgets.QLabel(self.tab)
        self.skinThicknessLabel.setGeometry(QtCore.QRect(20, 300, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.skinThicknessLabel.setFont(font)
        self.skinThicknessLabel.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.skinThicknessLabel.setObjectName("skinThicknessLabel")
        self.insulinLabel = QtWidgets.QLabel(self.tab)
        self.insulinLabel.setGeometry(QtCore.QRect(530, 60, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.insulinLabel.setFont(font)
        self.insulinLabel.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.insulinLabel.setObjectName("insulinLabel")
        self.bmiLabel = QtWidgets.QLabel(self.tab)
        self.bmiLabel.setGeometry(QtCore.QRect(530, 140, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.bmiLabel.setFont(font)
        self.bmiLabel.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.bmiLabel.setObjectName("bmiLabel")
        self.diabetesPedigreeFunctionLabel = QtWidgets.QLabel(self.tab)
        self.diabetesPedigreeFunctionLabel.setGeometry(QtCore.QRect(430, 220, 231, 41))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.diabetesPedigreeFunctionLabel.setFont(font)
        self.diabetesPedigreeFunctionLabel.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.diabetesPedigreeFunctionLabel.setObjectName("diabetesPedigreeFunctionLabel")
        self.ageLabel = QtWidgets.QLabel(self.tab)
        self.ageLabel.setGeometry(QtCore.QRect(530, 300, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.ageLabel.setFont(font)
        self.ageLabel.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.ageLabel.setObjectName("ageLabel")
        self.pregnanciesError = QtWidgets.QLabel(self.tab)
        self.pregnanciesError.setGeometry(QtCore.QRect(180, 110, 211, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pregnanciesError.setFont(font)
        self.pregnanciesError.setStyleSheet("background-color: rgb(255, 255, 255);\n"
                                            "color: rgb(255, 0, 0);")
        self.pregnanciesError.setText("")
        self.pregnanciesError.setObjectName("pregnanciesError")
        self.glucoseError = QtWidgets.QLabel(self.tab)
        self.glucoseError.setGeometry(QtCore.QRect(180, 190, 211, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.glucoseError.setFont(font)
        self.glucoseError.setStyleSheet("background-color: rgb(255, 255, 255);\n"
                                        "color: rgb(255, 0, 0);")
        self.glucoseError.setText("")
        self.glucoseError.setObjectName("glucoseError")
        self.bloodPresureError = QtWidgets.QLabel(self.tab)
        self.bloodPresureError.setGeometry(QtCore.QRect(180, 270, 211, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.bloodPresureError.setFont(font)
        self.bloodPresureError.setStyleSheet("background-color: rgb(255, 255, 255);\n"
                                             "color: rgb(255, 0, 0);")
        self.bloodPresureError.setText("")
        self.bloodPresureError.setObjectName("bloodPresureError")
        self.skinThicknessError = QtWidgets.QLabel(self.tab)
        self.skinThicknessError.setGeometry(QtCore.QRect(180, 350, 211, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.skinThicknessError.setFont(font)
        self.skinThicknessError.setStyleSheet("background-color: rgb(255, 255, 255);\n"
                                              "color: rgb(255, 0, 0);")
        self.skinThicknessError.setText("")
        self.skinThicknessError.setObjectName("skinThicknessError")
        self.ageError = QtWidgets.QLabel(self.tab)
        self.ageError.setGeometry(QtCore.QRect(690, 350, 211, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.ageError.setFont(font)
        self.ageError.setStyleSheet("background-color: rgb(255, 255, 255);\n"
                                    "color: rgb(255, 0, 0);")
        self.ageError.setText("")
        self.ageError.setObjectName("ageError")
        self.diabetesPedigreeFunctionError = QtWidgets.QLabel(self.tab)
        self.diabetesPedigreeFunctionError.setGeometry(QtCore.QRect(690, 270, 211, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.diabetesPedigreeFunctionError.setFont(font)
        self.diabetesPedigreeFunctionError.setStyleSheet("background-color: rgb(255, 255, 255);\n"
                                                         "color: rgb(255, 0, 0);")
        self.diabetesPedigreeFunctionError.setText("")
        self.diabetesPedigreeFunctionError.setObjectName("diabetesPedigreeFunctionError")
        self.bmiError = QtWidgets.QLabel(self.tab)
        self.bmiError.setGeometry(QtCore.QRect(690, 190, 211, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.bmiError.setFont(font)
        self.bmiError.setStyleSheet("background-color: rgb(255, 255, 255);\n"
                                    "color: rgb(255, 0, 0);")
        self.bmiError.setText("")
        self.bmiError.setObjectName("bmiError")
        self.insulinError = QtWidgets.QLabel(self.tab)
        self.insulinError.setGeometry(QtCore.QRect(690, 110, 211, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.insulinError.setFont(font)
        self.insulinError.setStyleSheet("background-color: rgb(255, 255, 255);\n"
                                        "color: rgb(255, 0, 0);")
        self.insulinError.setText("")
        self.insulinError.setObjectName("insulinError")
        self.typeError = QtWidgets.QLabel(self.tab)
        self.typeError.setGeometry(QtCore.QRect(440, 380, 211, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.typeError.setFont(font)
        self.typeError.setStyleSheet("background-color: rgb(255, 255, 255);\n"
                                     "color: rgb(255, 0, 0);")
        self.typeError.setText("")
        self.typeError.setObjectName("typeError")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setStyleSheet(
            "background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(0, 0, 0, 255), stop:0.33 rgba(0, 0, 0, 255), stop:0.34 rgba(255, 30, 30, 255), stop:0.66 rgba(255, 0, 0, 255), stop:0.67 rgba(255, 255, 0, 255), stop:1 rgba(255, 255, 0, 255));")
        self.tab_2.setObjectName("tab_2")
        self.labelImport = QtWidgets.QLabel(self.tab_2)
        self.labelImport.setGeometry(QtCore.QRect(150, 240, 421, 51))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(18)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.labelImport.setFont(font)
        self.labelImport.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.labelImport.setObjectName("labelImport")
        self.browse = QtWidgets.QPushButton(self.tab_2)
        self.browse.setGeometry(QtCore.QRect(590, 240, 241, 51))
        self.browse.clicked.connect(self.getfiles)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(20)
        self.browse.setFont(font)
        self.browse.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.browse.setObjectName("browse")
        self.deepLearningBrowse = QtWidgets.QCheckBox(self.tab_2)
        self.deepLearningBrowse.setGeometry(QtCore.QRect(590, 320, 231, 41))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.deepLearningBrowse.setFont(font)
        self.deepLearningBrowse.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.deepLearningBrowse.setObjectName("deepLearningBrowse")
        self.machineLearningImport = QtWidgets.QCheckBox(self.tab_2)
        self.machineLearningImport.setGeometry(QtCore.QRect(150, 330, 231, 41))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.machineLearningImport.setFont(font)
        self.machineLearningImport.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.machineLearningImport.setObjectName("machineLearningImport")
        self.typeError2 = QtWidgets.QLabel(self.tab_2)
        self.typeError2.setGeometry(QtCore.QRect(370, 390, 211, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.typeError2.setFont(font)
        self.typeError2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
                                      "color: rgb(255, 0, 0);")
        self.typeError2.setText("")
        self.typeError2.setObjectName("typeError2")
        self.predict2 = QtWidgets.QPushButton(self.tab_2)
        self.predict2.clicked.connect(self.clickPredictXLSX)
        self.predict2.setGeometry(QtCore.QRect(240, 440, 461, 61))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.predict2.setFont(font)
        self.predict2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.predict2.setObjectName("predict2")
        self.statusPrediction = QtWidgets.QLabel(self.tab_2)
        self.statusPrediction.setGeometry(QtCore.QRect(240, 530, 461, 31))
        self.statusPrediction.setStyleSheet("background-color: rgb(255, 255, 255);\n"
                                            "color: rgb(255, 0, 0);")
        self.statusPrediction.setText("")
        self.statusPrediction.setObjectName("statusPrediction")
        self.tabWidget.addTab(self.tab_2, "")
        Diabete.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Diabete)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1098, 21))
        self.menubar.setObjectName("menubar")
        Diabete.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Diabete)
        self.statusbar.setObjectName("statusbar")
        Diabete.setStatusBar(self.statusbar)

        self.retranslateUi(Diabete)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Diabete)

    def retranslateUi(self, Diabete):
        _translate = QtCore.QCoreApplication.translate
        Diabete.setWindowTitle(_translate("Diabete", "DiabeteMeter"))
        self.machineLearningCheckbox.setText(_translate("Diabete", "Machine Learning"))
        self.deepLearningCheckbox.setText(_translate("Diabete", "Deep learning"))
        self.pushButton.setText(_translate("Diabete", "Predict"))
        self.pregnanciesLabel.setText(_translate("Diabete", "Pregnancies"))
        self.glucoseLabel.setText(_translate("Diabete", "Glucose"))
        self.bloodPresureLabel.setText(_translate("Diabete", "Blood presure"))
        self.skinThicknessLabel.setText(_translate("Diabete", "Skin thickness"))
        self.insulinLabel.setText(_translate("Diabete", "Insulin"))
        self.bmiLabel.setText(_translate("Diabete", "BMI"))
        self.diabetesPedigreeFunctionLabel.setText(_translate("Diabete", "Diabetes Pedigree Function"))
        self.ageLabel.setText(_translate("Diabete", "Age"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Diabete", "Tab 1"))
        self.labelImport.setText(_translate("Diabete", ""))
        self.browse.setText(_translate("Diabete", "Browse"))
        self.deepLearningBrowse.setText(_translate("Diabete", "Deep Learning"))
        self.machineLearningImport.setText(_translate("Diabete", "Machine Learning"))
        self.predict2.setText(_translate("Diabete", "Predict"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Diabete", "Tab 2"))
